package io.github.sdxqw.pong2.server;

import io.github.sdxqw.logger.Logger;
import io.github.sdxqw.pong2.PongGame;
import lombok.Getter;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.UUID;

@Getter
public class PongServer {
    private final PongServerInfo dbInfo = PongServerInfo.Database;
    private final PongGame game;
    private Connection connectionPool = null;
    private volatile boolean connectionAlive = false;

    public PongServer(PongGame game) {
        this.game = game;
        Logger.info("Starting PongServer...");
        Logger.info("DataBase URL: %s", dbInfo.getDbUrl());
        Logger.info("DataBase User: %s", dbInfo.getDbUser());
        Logger.info("DataBase Password: %s", dbInfo.getDbPassword());

        try {
            connectionPool = DriverManager.getConnection(dbInfo.getDbUrl(), dbInfo.getDbUser(), dbInfo.getDbPassword());
            if (!connectionPool.isClosed() || connectionPool != null) {
                connectionAlive = true;
                Logger.info("Server started successfully!");
            } else {
                connectionAlive = false;
                Logger.error("Failed to initialize connection pool: %s", dbInfo.getDbUrl());
            }
        } catch (SQLException e) {
            Logger.error("Failed to connect to the database: %s", e.getMessage());
        }
    }

    public void closeConnection() {
        if (connectionPool != null) {
            try {
                Logger.info("Closing connection to database: %s", dbInfo.getDbUrl());
                connectionAlive = false;
                connectionPool.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
    }

    private ResultSet readFromDatabase(UUID sessionID) {
        if (!isConnectionAlive())
            return null;

        try {
            PreparedStatement statement = connectionPool.prepareStatement("SELECT * FROM Users WHERE session_id = ?", ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_UPDATABLE);
            statement.setString(1, sessionID.toString());
            return statement.executeQuery();
        } catch (SQLException e) {
            Logger.error("Failed to execute database query: %s", e.getMessage());
            return null;
        }
    }


    public List<String> getAllUsers() {
        List<String> users = new ArrayList<>();

        if (!isConnectionAlive()) {
            return users;
        }

        try {
            PreparedStatement statement = connectionPool.prepareStatement("SELECT username FROM Users");
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                String userName = resultSet.getString("username");
                users.add(userName);
            }

            resultSet.close();
        } catch (SQLException e) {
            Logger.error("Failed to retrieve users from the database: %s", e.getMessage());
        }

        return users;
    }

    public List<String> getAllHighestScores() {
        List<String> scores = new ArrayList<>();

        if (!isConnectionAlive()) {
            return scores;
        }

        try {
            PreparedStatement statement = connectionPool.prepareStatement("SELECT highest_scores FROM Users");
            ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                String highScore = resultSet.getString("highest_scores");
                scores.add(highScore);
            }

            resultSet.close();
        } catch (SQLException e) {
            Logger.error("Failed to retrieve highest scores from the database: %s", e.getMessage());
        }

        return scores;
    }

    public void getUserName(UUID sessionID) {
        if (!isConnectionAlive()) {
            game.userData.setUserName("Player" + Math.abs(new Random().nextInt() & 100) + 1);
        } else {
            ResultSet resultSet = readFromDatabase(sessionID);
            if (resultSet != null) {
                try {
                    if (resultSet.next()) {
                        game.userData.setUserName(resultSet.getString("username"));
                    } else {
                        String autoGeneratedUsername = "Player" + Math.abs(new Random().nextInt() & 100) + 1;
                        saveNewUser(sessionID, autoGeneratedUsername);
                        game.userData.setUserName(autoGeneratedUsername);
                    }
                } catch (SQLException e) {
                    if (e instanceof SQLNonTransientConnectionException) {
                        game.userData.setUserName("Player" + Math.abs(new Random().nextInt() & 100) + 1);
                        Logger.error("Failed to retrieve username from ResultSet: Database connection is closed");
                    } else {
                        throw new RuntimeException("Failed to retrieve username from ResultSet", e);
                    }
                } finally {
                    try {
                        resultSet.close();
                    } catch (SQLException e) {
                        Logger.warn("Failed to close ResultSet", e);
                    }
                }
            } else {
                String autoGeneratedUsername = "Player" + Math.abs(new Random().nextInt() & 100) + 1;
                saveNewUser(sessionID, autoGeneratedUsername);
                game.userData.setUserName(autoGeneratedUsername);
            }
        }
    }

    private void saveNewUser(UUID sessionID, String username) {
        try {
            PreparedStatement statement = connectionPool.prepareStatement("INSERT INTO Users (session_id, username, highest_scores) VALUES (?, ?, 0)");
            statement.setString(1, sessionID.toString());
            statement.setString(2, username);
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new RuntimeException("Failed to save new user in the database", e);
        }
    }

    public void getHighestScore(UUID sessionID) {
        if (!isConnectionAlive()) {
            game.userData.setHighScore(String.valueOf(game.score.getHighestPlayer1Score()));
        } else {
            ResultSet resultSet = readFromDatabase(sessionID);
            if (resultSet != null) {
                try {
                    if (resultSet.next()) {
                        game.userData.setHighScore(resultSet.getString("highest_scores"));
                    } else {
                        game.userData.setHighScore(String.valueOf(game.score.getHighestPlayer1Score()));
                    }
                } catch (SQLException e) {
                    throw new RuntimeException("Failed to retrieve username from ResultSet", e);
                } finally {
                    try {
                        resultSet.close();
                    } catch (SQLException e) {
                        Logger.warn("Failed to close ResultSet", e);
                    }
                }
            } else {
                game.userData.setHighScore(String.valueOf(game.score.getHighestPlayer1Score()));
            }
        }
    }

    public void saveHighestScore(UUID sessionID, int highestScore) {
        if (!isConnectionAlive()) {
            game.userData.setHighScore(String.valueOf(highestScore));
        } else {
            try {
                PreparedStatement selectStatement = connectionPool.prepareStatement(
                        "SELECT * FROM Users WHERE session_id = ?",
                        ResultSet.TYPE_FORWARD_ONLY,
                        ResultSet.CONCUR_UPDATABLE);

                selectStatement.setString(1, sessionID.toString());
                ResultSet resultSet = selectStatement.executeQuery();

                if (resultSet.next()) {
                    int currentHighScore = resultSet.getInt("highest_scores");
                    if (highestScore > currentHighScore) {
                        resultSet.updateInt("highest_scores", highestScore);
                        resultSet.updateRow();
                        game.userData.setHighScore(String.valueOf(highestScore));
                    }
                }

                resultSet.close();
                selectStatement.close();
            } catch (SQLException e) {
                if (e instanceof SQLNonTransientConnectionException) {
                    game.userData.setHighScore(String.valueOf(highestScore));
                    connectionAlive = false;
                } else {
                    throw new RuntimeException("Failed to update highest score in the database", e);
                }
            }
        }
    }


    @Getter
    private enum PongServerInfo {
        Database("jdbc:mariadb://localhost:3306/pong", "root", "123");

        final String dbUrl;
        final String dbUser;
        final String dbPassword;

        PongServerInfo(String dbUrl, String dbUser, String dbPassword) {
            this.dbUrl = dbUrl;
            this.dbUser = dbUser;
            this.dbPassword = dbPassword;
        }
    }
}
